replicaCount: 1

image:
  repository: localhost/heart-risk-app
  pullPolicy: Never
  tag: "local"

service:
  type: NodePort
  port: 8501
  nodePort: 30501

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

